<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'label' => 'Dashboard',
                'url' => 'dashboard',
                'icon' => '<i class="nav-icon la la-dashboard "></i>',
                'permission' => NULL,
                'parent_id' => 67,
                'lft' => 3,
                'rgt' => 4,
                'depth' => 2,
                'created_at' => '2020-12-16 06:58:25',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            1 => 
            array (
                'id' => 2,
                'label' => 'Employee Records',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-user"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 8,
                'rgt' => 37,
                'depth' => 1,
                'created_at' => '2020-12-16 07:00:21',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            2 => 
            array (
                'id' => 3,
                'label' => 'Award And Recognition\'s',
                'url' => 'awardandrecognition',
                'icon' => '<i class=\'nav-icon la la-trophy\'></i>',
                'permission' => 'award_and_recognitions_list',
                'parent_id' => 2,
                'lft' => 13,
                'rgt' => 14,
                'depth' => 2,
                'created_at' => '2020-12-16 07:11:38',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            3 => 
            array (
                'id' => 4,
                'label' => 'Employees',
                'url' => 'employee',
                'icon' => '<i class=\'nav-icon la la-user-plus\'></i>',
                'permission' => 'employees_list',
                'parent_id' => 2,
                'lft' => 9,
                'rgt' => 10,
                'depth' => 2,
                'created_at' => '2020-12-16 07:12:30',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            4 => 
            array (
                'id' => 5,
                'label' => 'Government Examinations',
                'url' => 'governmentexamination',
                'icon' => '<i class=\'nav-icon la la-industry\'></i>',
                'permission' => 'government_examinations_list',
                'parent_id' => 2,
                'lft' => 23,
                'rgt' => 24,
                'depth' => 2,
                'created_at' => '2020-12-16 07:13:14',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            5 => 
            array (
                'id' => 6,
                'label' => 'Supporting Documents',
                'url' => 'supportingdocument',
                'icon' => '<i class=\'nav-icon la la-file-alt\'></i>',
                'permission' => 'supporting_documents_list',
                'parent_id' => 2,
                'lft' => 31,
                'rgt' => 32,
                'depth' => 2,
                'created_at' => '2020-12-16 07:13:57',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            6 => 
            array (
                'id' => 7,
                'label' => 'Training & Seminars',
                'url' => 'trainingandseminar',
                'icon' => '<i class=\'nav-icon la la-bicycle\'></i>',
                'permission' => 'training_and_seminars_list',
                'parent_id' => 2,
                'lft' => 33,
                'rgt' => 34,
                'depth' => 2,
                'created_at' => '2020-12-16 07:20:23',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            7 => 
            array (
                'id' => 8,
                'label' => 'Work Experiences',
                'url' => 'workexperience',
                'icon' => '<i class=\'nav-icon la la-bolt\'></i>',
                'permission' => 'work_experiences_list',
                'parent_id' => 2,
                'lft' => 35,
                'rgt' => 36,
                'depth' => 2,
                'created_at' => '2020-12-16 07:20:46',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            8 => 
            array (
                'id' => 9,
                'label' => 'App Settings',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-cog"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 66,
                'rgt' => 129,
                'depth' => 1,
                'created_at' => '2020-12-16 07:21:07',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            9 => 
            array (
                'id' => 10,
                'label' => 'Blood Type',
                'url' => 'bloodtype',
                'icon' => '<i class=\'nav-icon la la-eyedropper\'></i>',
                'permission' => 'blood_types_list',
                'parent_id' => 9,
                'lft' => 71,
                'rgt' => 72,
                'depth' => 2,
                'created_at' => '2020-12-16 07:21:32',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            10 => 
            array (
                'id' => 11,
                'label' => 'Citizenship',
                'url' => 'citizenship',
                'icon' => '<i class=\'nav-icon la la-flag-o\'></i>',
                'permission' => 'citizenships_list',
                'parent_id' => 9,
                'lft' => 73,
                'rgt' => 74,
                'depth' => 2,
                'created_at' => '2020-12-16 07:21:51',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            11 => 
            array (
                'id' => 12,
                'label' => 'Civil Status',
                'url' => 'civilstatus',
                'icon' => '<i class=\'nav-icon la la-neuter\'></i>',
                'permission' => 'civil_statuses_list',
                'parent_id' => 9,
                'lft' => 75,
                'rgt' => 76,
                'depth' => 2,
                'created_at' => '2020-12-16 07:22:14',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            12 => 
            array (
                'id' => 13,
                'label' => 'Gender',
                'url' => 'gender',
                'icon' => '<i class=\'nav-icon la la-venus\'></i>',
                'permission' => 'genders_list',
                'parent_id' => 9,
                'lft' => 91,
                'rgt' => 92,
                'depth' => 2,
                'created_at' => '2020-12-16 07:22:32',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            13 => 
            array (
                'id' => 14,
                'label' => 'Religion',
                'url' => 'religion',
                'icon' => '<i class=\'nav-icon la la-church\'></i>',
                'permission' => 'religions_list',
                'parent_id' => 9,
                'lft' => 119,
                'rgt' => 120,
                'depth' => 2,
                'created_at' => '2020-12-16 07:22:56',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            14 => 
            array (
                'id' => 15,
                'label' => 'Administrator Only',
                'url' => NULL,
                'icon' => NULL,
                'permission' => 'admin_view',
                'parent_id' => NULL,
                'lft' => 130,
                'rgt' => 131,
                'depth' => 1,
                'created_at' => '2020-12-16 07:23:11',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            15 => 
            array (
                'id' => 16,
                'label' => 'Audit Trails',
                'url' => 'audittrail',
                'icon' => '<i class=\'nav-icon la la-history\'></i>',
                'permission' => 'audit_trails_list',
                'parent_id' => NULL,
                'lft' => 132,
                'rgt' => 133,
                'depth' => 1,
                'created_at' => '2020-12-16 07:26:27',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            16 => 
            array (
                'id' => 17,
                'label' => 'Authentication',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-users"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 134,
                'rgt' => 141,
                'depth' => 1,
                'created_at' => '2020-12-16 07:27:02',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            17 => 
            array (
                'id' => 18,
                'label' => 'Users',
                'url' => 'user',
                'icon' => '<i class="nav-icon la la-user"></i>',
                'permission' => 'users_list',
                'parent_id' => 17,
                'lft' => 135,
                'rgt' => 136,
                'depth' => 2,
                'created_at' => '2020-12-16 07:27:32',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            18 => 
            array (
                'id' => 19,
                'label' => 'Roles',
                'url' => 'role',
                'icon' => '<i class="nav-icon la la-id-badge"></i>',
                'permission' => 'roles_list',
                'parent_id' => 17,
                'lft' => 137,
                'rgt' => 138,
                'depth' => 2,
                'created_at' => '2020-12-16 07:27:49',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            19 => 
            array (
                'id' => 20,
                'label' => 'Permissions',
                'url' => 'permission',
                'icon' => '<i class="nav-icon la la-key"></i>',
                'permission' => 'permissions_list',
                'parent_id' => 17,
                'lft' => 139,
                'rgt' => 140,
                'depth' => 2,
                'created_at' => '2020-12-16 07:28:08',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            20 => 
            array (
                'id' => 21,
                'label' => 'Advanced',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-cogs"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 142,
                'rgt' => 151,
                'depth' => 1,
                'created_at' => '2020-12-16 07:28:27',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            21 => 
            array (
                'id' => 22,
                'label' => 'File Manager',
                'url' => 'elfinder',
                'icon' => '<i class="nav-icon la la-files-o"></i>',
                'permission' => 'advanced_file_manager',
                'parent_id' => 21,
                'lft' => 143,
                'rgt' => 144,
                'depth' => 2,
                'created_at' => '2020-12-16 07:30:40',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            22 => 
            array (
                'id' => 23,
                'label' => 'Backups',
                'url' => 'backup',
                'icon' => '<i class=\'nav-icon la la-hdd-o\'></i>',
                'permission' => 'advanced_backups',
                'parent_id' => 21,
                'lft' => 145,
                'rgt' => 146,
                'depth' => 2,
                'created_at' => '2020-12-16 07:31:21',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            23 => 
            array (
                'id' => 24,
                'label' => 'Logs',
                'url' => 'log',
                'icon' => '<i class=\'nav-icon la la-terminal\'></i>',
                'permission' => 'advanced_logs',
                'parent_id' => 21,
                'lft' => 147,
                'rgt' => 148,
                'depth' => 2,
                'created_at' => '2020-12-16 07:31:47',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            24 => 
            array (
                'id' => 25,
                'label' => 'Settings',
                'url' => 'setting',
                'icon' => '<i class=\'nav-icon la la-cog\'></i>',
                'permission' => 'advanced_settings',
                'parent_id' => 21,
                'lft' => 149,
                'rgt' => 150,
                'depth' => 2,
                'created_at' => '2020-12-16 07:32:02',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            25 => 
            array (
                'id' => 26,
                'label' => 'Menu',
                'url' => 'menu',
                'icon' => '<i class=\'nav-icon la la-list\'></i>',
                'permission' => 'menus_list',
                'parent_id' => NULL,
                'lft' => 152,
                'rgt' => 153,
                'depth' => 1,
                'created_at' => '2020-12-16 07:32:42',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            26 => 
            array (
                'id' => 28,
                'label' => 'Family & Contacts',
                'url' => 'familydata',
                'icon' => '<i class=\'nav-icon las la-clone\'></i>',
                'permission' => 'family_datas_list',
                'parent_id' => 2,
                'lft' => 21,
                'rgt' => 22,
                'depth' => 2,
                'created_at' => '2020-12-31 09:52:25',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            27 => 
            array (
                'id' => 29,
                'label' => 'Relation',
                'url' => 'relation',
                'icon' => '<i class=\'nav-icon las la-clone\'></i>',
                'permission' => 'relations_list',
                'parent_id' => 9,
                'lft' => 117,
                'rgt' => 118,
                'depth' => 2,
                'created_at' => '2021-01-05 02:25:36',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            28 => 
            array (
                'id' => 30,
                'label' => 'Educational Level',
                'url' => 'educationallevel',
                'icon' => '<i class="nav-icon las la-graduation-cap"></i>',
                'permission' => 'educational_levels_list',
                'parent_id' => 9,
                'lft' => 85,
                'rgt' => 86,
                'depth' => 2,
                'created_at' => '2021-01-07 05:08:46',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            29 => 
            array (
                'id' => 31,
                'label' => 'Educational Backgrounds',
                'url' => 'educationalbackground',
                'icon' => '<i class=\'nav-icon las la-graduation-cap\'></i>',
                'permission' => 'educational_backgrounds_list',
                'parent_id' => 2,
                'lft' => 19,
                'rgt' => 20,
                'depth' => 2,
                'created_at' => '2021-01-07 05:47:39',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            30 => 
            array (
                'id' => 32,
                'label' => 'Medical Information',
                'url' => 'medicalinformation',
                'icon' => '<i class=\'nav-icon la la-medkit\'></i>',
                'permission' => 'medical_informations_list',
                'parent_id' => 2,
                'lft' => 25,
                'rgt' => 26,
                'depth' => 2,
                'created_at' => '2021-01-07 10:04:28',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            31 => 
            array (
                'id' => 33,
                'label' => 'Professional Organizations',
                'url' => 'professionalorg',
                'icon' => '<i class=\'nav-icon la la-address-card\'></i>',
                'permission' => 'professional_orgs_list',
                'parent_id' => 2,
                'lft' => 27,
                'rgt' => 28,
                'depth' => 2,
                'created_at' => '2021-01-07 12:43:27',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            32 => 
            array (
                'id' => 34,
                'label' => 'Beneficiaries',
                'url' => 'beneficiary',
                'icon' => '<i class=\'nav-icon la la-user-shield\'></i>',
                'permission' => 'benefeciaries_list',
                'parent_id' => 2,
                'lft' => 15,
                'rgt' => 16,
                'depth' => 2,
                'created_at' => '2021-01-08 07:10:38',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            33 => 
            array (
                'id' => 35,
                'label' => 'Dependents',
                'url' => 'dependents',
                'icon' => '<i class=\'nav-icon las la-baby\'></i>',
                'permission' => 'dependents_list',
                'parent_id' => 2,
                'lft' => 17,
                'rgt' => 18,
                'depth' => 2,
                'created_at' => '2021-01-09 07:52:23',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            34 => 
            array (
                'id' => 36,
                'label' => 'Skills & Talents',
                'url' => 'skillandtalent',
                'icon' => '<i class=\'nav-icon las la-music\'></i>',
                'permission' => 'skill_and_talents_list',
                'parent_id' => 2,
                'lft' => 29,
                'rgt' => 30,
                'depth' => 2,
                'created_at' => '2021-01-09 11:08:45',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            35 => 
            array (
                'id' => 37,
                'label' => 'Payment Method',
                'url' => 'paymentmethod',
                'icon' => '<i class=\'nav-icon las la-credit-card\'></i>',
                'permission' => 'payment_methods_list',
                'parent_id' => 9,
                'lft' => 111,
                'rgt' => 112,
                'depth' => 2,
                'created_at' => '2021-01-11 09:58:11',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            36 => 
            array (
                'id' => 38,
                'label' => 'Pay Basis',
                'url' => 'paybasis',
                'icon' => '<i class=\'nav-icon las la-calendar-alt\'></i>',
                'permission' => 'pay_bases_list',
                'parent_id' => 9,
                'lft' => 109,
                'rgt' => 110,
                'depth' => 2,
                'created_at' => '2021-01-12 04:58:02',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            37 => 
            array (
                'id' => 39,
                'label' => 'Job Status',
                'url' => 'jobstatus',
                'icon' => '<i class=\'nav-icon las la-user-tag\'></i>',
                'permission' => 'job_statuses_list',
                'parent_id' => 9,
                'lft' => 99,
                'rgt' => 100,
                'depth' => 2,
                'created_at' => '2021-01-12 05:36:56',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            38 => 
            array (
                'id' => 40,
                'label' => 'Employment Status',
                'url' => 'employmentstatus',
                'icon' => '<i class=\'nav-icon las la-user-tie\'></i>',
                'permission' => 'employment_statuses_list',
                'parent_id' => 9,
                'lft' => 89,
                'rgt' => 90,
                'depth' => 2,
                'created_at' => '2021-01-12 07:05:31',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            39 => 
            array (
                'id' => 41,
                'label' => 'Company',
                'url' => 'company',
                'icon' => '<i class=\'nav-icon las la-building\'></i>',
                'permission' => 'companies_list',
                'parent_id' => 9,
                'lft' => 77,
                'rgt' => 78,
                'depth' => 2,
                'created_at' => '2021-01-12 07:30:05',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            40 => 
            array (
                'id' => 42,
                'label' => 'Location',
                'url' => 'location',
                'icon' => '<i class=\'nav-icon las la-map-marked-alt\'></i>',
                'permission' => 'locations_list',
                'parent_id' => 9,
                'lft' => 105,
                'rgt' => 106,
                'depth' => 2,
                'created_at' => '2021-01-12 10:59:14',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            41 => 
            array (
                'id' => 43,
                'label' => 'Department',
                'url' => 'department',
                'icon' => '<i class=\'nav-icon las la-layer-group\'></i>',
                'permission' => 'departments_list',
                'parent_id' => 9,
                'lft' => 81,
                'rgt' => 82,
                'depth' => 2,
                'created_at' => '2021-01-12 13:29:06',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            42 => 
            array (
                'id' => 44,
                'label' => 'Division',
                'url' => 'division',
                'icon' => '<i class=\'nav-icon las la-star-half-alt\'></i>',
                'permission' => 'divisions_list',
                'parent_id' => 9,
                'lft' => 83,
                'rgt' => 84,
                'depth' => 2,
                'created_at' => '2021-01-12 13:44:42',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            43 => 
            array (
                'id' => 45,
                'label' => 'Section',
                'url' => 'section',
                'icon' => '<i class=\'nav-icon las la-stream\'></i>',
                'permission' => 'sections_list',
                'parent_id' => 9,
                'lft' => 121,
                'rgt' => 122,
                'depth' => 2,
                'created_at' => '2021-01-12 15:29:49',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            44 => 
            array (
                'id' => 46,
                'label' => 'Position',
                'url' => 'position',
                'icon' => '<i class=\'nav-icon las la-hard-hat\'></i>',
                'permission' => 'positions_list',
                'parent_id' => 9,
                'lft' => 113,
                'rgt' => 114,
                'depth' => 2,
                'created_at' => '2021-01-13 04:50:01',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            45 => 
            array (
                'id' => 47,
                'label' => 'Level',
                'url' => 'level',
                'icon' => '<i class=\'nav-icon las la-balance-scale\'></i>',
                'permission' => 'levels_list',
                'parent_id' => 9,
                'lft' => 103,
                'rgt' => 104,
                'depth' => 2,
                'created_at' => '2021-01-13 23:10:39',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            46 => 
            array (
                'id' => 48,
                'label' => 'Rank',
                'url' => 'rank',
                'icon' => '<i class=\'nav-icon las la-chalkboard\'></i>',
                'permission' => 'ranks_list',
                'parent_id' => 9,
                'lft' => 115,
                'rgt' => 116,
                'depth' => 2,
                'created_at' => '2021-01-13 23:30:25',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            47 => 
            array (
                'id' => 49,
                'label' => 'Grouping',
                'url' => 'grouping',
                'icon' => '<i class=\'nav-icon las la-object-group\'></i>',
                'permission' => 'groupings_list',
                'parent_id' => 9,
                'lft' => 95,
                'rgt' => 96,
                'depth' => 2,
                'created_at' => '2021-01-14 14:24:53',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            48 => 
            array (
                'id' => 50,
                'label' => 'Days Per Year',
                'url' => 'daysperyear',
                'icon' => '<i class=\'nav-icon las la-calendar\'></i>',
                'permission' => 'days_per_years_list',
                'parent_id' => 9,
                'lft' => 79,
                'rgt' => 80,
                'depth' => 2,
                'created_at' => '2021-01-16 02:11:31',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            49 => 
            array (
                'id' => 51,
                'label' => 'Employment Info',
                'url' => 'employmentinformation',
                'icon' => '<i class=\'nav-icon las la-address-book\'></i>',
                'permission' => 'employment_informations_list',
                'parent_id' => 2,
                'lft' => 11,
                'rgt' => 12,
                'depth' => 2,
                'created_at' => '2021-01-18 06:07:20',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            50 => 
            array (
                'id' => 52,
                'label' => 'Employment Info Fields',
                'url' => 'employmentinfofield',
                'icon' => '<i class=\'nav-icon las la-table\'></i>',
                'permission' => 'employment_info_fields_list',
                'parent_id' => 9,
                'lft' => 87,
                'rgt' => 88,
                'depth' => 2,
                'created_at' => '2021-01-21 16:45:46',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            51 => 
            array (
                'id' => 53,
                'label' => 'Performance Mgt.',
                'url' => NULL,
                'icon' => '<i class="nav-icon las la-chalkboard"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 60,
                'rgt' => 65,
                'depth' => 1,
                'created_at' => '2021-01-28 14:40:46',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            52 => 
            array (
                'id' => 54,
                'label' => 'Performance Appraisals',
                'url' => 'performanceappraisal',
                'icon' => '<i class=\'nav-icon la la-hands-helping\'></i>',
                'permission' => 'performance_appraisals_list',
                'parent_id' => 53,
                'lft' => 63,
                'rgt' => 64,
                'depth' => 2,
                'created_at' => '2021-01-28 14:51:05',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            53 => 
            array (
                'id' => 55,
                'label' => 'Appraisal Types',
                'url' => 'appraisaltype',
                'icon' => '<i class=\'nav-icon las la-project-diagram\'></i>',
                'permission' => 'appraisal_types_list',
                'parent_id' => 9,
                'lft' => 69,
                'rgt' => 70,
                'depth' => 2,
                'created_at' => '2021-01-29 02:51:46',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            54 => 
            array (
                'id' => 56,
                'label' => 'Appraisal Interpretations',
                'url' => 'appraisalinterpretation',
                'icon' => '<i class=\'nav-icon las la-award\'></i>',
                'permission' => 'appraisal_interpretations_list',
                'parent_id' => 9,
                'lft' => 67,
                'rgt' => 68,
                'depth' => 2,
                'created_at' => '2021-01-29 03:12:19',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            55 => 
            array (
                'id' => 57,
                'label' => 'Offence Classifications',
                'url' => 'offenceclassification',
                'icon' => '<i class=\'nav-icon las la-grimace\'></i>',
                'permission' => 'offence_classifications_list',
                'parent_id' => 9,
                'lft' => 107,
                'rgt' => 108,
                'depth' => 2,
                'created_at' => '2021-02-08 20:06:19',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            56 => 
            array (
                'id' => 58,
                'label' => 'Gravity Of Sanction',
                'url' => 'gravityofsanction',
                'icon' => '<i class=\'nav-icon las la-dizzy\'></i>',
                'permission' => 'gravity_of_sanctions_list',
                'parent_id' => 9,
                'lft' => 93,
                'rgt' => 94,
                'depth' => 2,
                'created_at' => '2021-02-09 18:51:28',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            57 => 
            array (
                'id' => 59,
                'label' => 'Offence & Sanction',
                'url' => 'offenceandsanction',
                'icon' => '<i class=\'nav-icon las la-book-reader\'></i>',
                'permission' => 'offence_and_sanctions_list',
                'parent_id' => 53,
                'lft' => 61,
                'rgt' => 62,
                'depth' => 2,
                'created_at' => '2021-02-09 19:07:27',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            58 => 
            array (
                'id' => 60,
                'label' => 'Shift Schedules',
                'url' => 'shiftschedules',
                'icon' => '<i class=\'nav-icon las la-calendar\'></i>',
                'permission' => 'shift_schedules_list',
                'parent_id' => 61,
                'lft' => 53,
                'rgt' => 54,
                'depth' => 2,
                'created_at' => '2021-02-12 20:40:44',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            59 => 
            array (
                'id' => 61,
                'label' => 'Daily Time Records',
                'url' => NULL,
                'icon' => '<i class=\'nav-icon las la-hourglass-half\'></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 38,
                'rgt' => 55,
                'depth' => 1,
                'created_at' => '2021-02-12 20:44:32',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            60 => 
            array (
                'id' => 62,
                'label' => 'Employee Shift Schedules',
                'url' => 'employeeshiftschedule',
                'icon' => '<i class=\'nav-icon las la-business-time\'></i>',
                'permission' => 'employee_shift_schedules_list',
                'parent_id' => 61,
                'lft' => 43,
                'rgt' => 44,
                'depth' => 2,
                'created_at' => '2021-02-18 21:51:18',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            61 => 
            array (
                'id' => 63,
                'label' => 'Change Shift Schedules',
                'url' => 'changeshiftschedule',
                'icon' => '<i class=\'nav-icon las la-calendar-check\'></i>',
                'permission' => 'change_shift_schedules_list',
                'parent_id' => 61,
                'lft' => 45,
                'rgt' => 46,
                'depth' => 2,
                'created_at' => '2021-03-01 12:22:07',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            62 => 
            array (
                'id' => 64,
                'label' => 'Holidays',
                'url' => 'holiday',
                'icon' => '<i class=\'nav-icon las la-calendar-times\'></i>',
                'permission' => 'holidays_list',
                'parent_id' => 9,
                'lft' => 97,
                'rgt' => 98,
                'depth' => 2,
                'created_at' => '2021-03-12 13:26:50',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            63 => 
            array (
                'id' => 65,
                'label' => 'Web Artisan Tinker',
                'url' => 'tinker',
                'icon' => '<i class=\'nav-icon lab la-laravel\'></i>',
                'permission' => 'admin_web_tinker',
                'parent_id' => NULL,
                'lft' => 154,
                'rgt' => 155,
                'depth' => 1,
                'created_at' => '2021-04-04 23:55:28',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            64 => 
            array (
                'id' => 66,
                'label' => 'DTR Logs',
                'url' => 'dtrlogs',
                'icon' => '<i class=\'nav-icon las la-calendar-alt\'></i>',
                'permission' => 'dtr_logs_list',
                'parent_id' => 61,
                'lft' => 41,
                'rgt' => 42,
                'depth' => 2,
                'created_at' => '2021-04-10 11:36:26',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            65 => 
            array (
                'id' => 67,
                'label' => 'Home',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-home"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 2,
                'rgt' => 7,
                'depth' => 1,
                'created_at' => '2021-08-04 15:43:05',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            66 => 
            array (
                'id' => 68,
                'label' => 'My Clock',
                'url' => '#',
                'icon' => '<li class="nav-item clock"> <a class="nav-link" href="#" title="Employee Time Clock"> <i class=\'nav-icon las la-clock\'></i>  My Clock </a> </li>',
                'permission' => 'employee_time_clock_show',
                'parent_id' => 67,
                'lft' => 5,
                'rgt' => 6,
                'depth' => 2,
                'created_at' => '2021-08-04 15:45:26',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            67 => 
            array (
                'id' => 69,
                'label' => 'Teams',
                'url' => 'team',
                'icon' => '<i class=\'nav-icon la la-users\'></i>',
                'permission' => 'teams_list',
                'parent_id' => 9,
                'lft' => 123,
                'rgt' => 124,
                'depth' => 2,
                'created_at' => '2021-08-05 19:20:11',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            68 => 
            array (
                'id' => 70,
                'label' => 'Payroll Periods',
                'url' => 'payrollperiod',
                'icon' => '<i class="nav-icon la la-money-check"></i>',
                'permission' => 'payroll_periods_list',
                'parent_id' => 71,
                'lft' => 57,
                'rgt' => 58,
                'depth' => 2,
                'created_at' => '2021-08-11 00:51:17',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            69 => 
            array (
                'id' => 71,
                'label' => 'Payrolls',
                'url' => NULL,
                'icon' => '<i class="nav-icon la la-th-list"></i>',
                'permission' => NULL,
                'parent_id' => NULL,
                'lft' => 56,
                'rgt' => 59,
                'depth' => 1,
                'created_at' => '2021-08-11 00:52:46',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            70 => 
            array (
                'id' => 72,
                'label' => 'Withholding Tax Versions',
                'url' => 'withholdingtaxversion',
                'icon' => '<i class=\'nav-icon la la-question\'></i>',
                'permission' => 'withholding_tax_versions_list',
                'parent_id' => 9,
                'lft' => 127,
                'rgt' => 128,
                'depth' => 2,
                'created_at' => '2021-08-17 00:35:55',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            71 => 
            array (
                'id' => 73,
                'label' => 'Withholding Tax Basis',
                'url' => 'withholdingtaxbasis',
                'icon' => '<i class=\'nav-icon la la-question\'></i>',
                'permission' => 'withholding_tax_bases_list',
                'parent_id' => 9,
                'lft' => 125,
                'rgt' => 126,
                'depth' => 2,
                'created_at' => '2021-08-19 20:21:27',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            72 => 
            array (
                'id' => 74,
                'label' => 'Daily Time Records',
                'url' => 'dailytimerecord',
                'icon' => '<i class=\'nav-icon las la-calendar-day\'></i>',
                'permission' => 'daily_time_records_list',
                'parent_id' => 61,
                'lft' => 39,
                'rgt' => 40,
                'depth' => 2,
                'created_at' => '2021-09-29 00:51:57',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            73 => 
            array (
                'id' => 75,
                'label' => 'Leave Types',
                'url' => 'leavetype',
                'icon' => '<i class=\'nav-icon las la-shapes\'></i>',
                'permission' => 'leave_types_list',
                'parent_id' => 9,
                'lft' => 101,
                'rgt' => 102,
                'depth' => 2,
                'created_at' => '2021-10-07 23:04:36',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            74 => 
            array (
                'id' => 76,
                'label' => 'Leave Credits',
                'url' => 'leavecredit',
                'icon' => '<i class=\'nav-icon las la-stream\'></i>',
                'permission' => 'leave_credits_list',
                'parent_id' => 61,
                'lft' => 51,
                'rgt' => 52,
                'depth' => 2,
                'created_at' => '2021-10-09 18:31:58',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            75 => 
            array (
                'id' => 77,
                'label' => 'Leave Applications',
                'url' => 'leaveapplication',
                'icon' => '<i class=\'nav-icon las la-calendar-plus\'></i>',
                'permission' => 'leave_applications_list',
                'parent_id' => 61,
                'lft' => 47,
                'rgt' => 48,
                'depth' => 2,
                'created_at' => '2021-10-12 19:33:54',
                'updated_at' => '2022-03-21 09:07:02',
            ),
            76 => 
            array (
                'id' => 78,
                'label' => 'Leave Approvers',
                'url' => 'leaveapprover',
                'icon' => '<i class=\'nav-icon las la-user-tie\'></i>',
                'permission' => 'leave_approvers_list',
                'parent_id' => 61,
                'lft' => 49,
                'rgt' => 50,
                'depth' => 2,
                'created_at' => '2021-10-18 01:48:57',
                'updated_at' => '2022-03-21 09:07:02',
            ),
        ));
        
        
    }
}